In [9]:
a = 1
b = 2
print(a + b)

3


In [10]:
print(a * b)

2


In [11]:
!uv add numpy==2.5.1

Resolved 2 packages in 14ms
Checked 1 package in 0.70ms


In [12]:
import numpy as np

In [13]:
arr = np.array([1,2,3, [1,3]])
print(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
print(arr)
print(f'维度：{arr.ndim}')
print(f'size:{arr.size}')
print(f'shape:{arr.shape}')
print(f'步幅:{arr.strides}') # (24, 8)

t = arr.T
print(t) # 和arr公用一块内存空间

[[1 2 3]
 [4 5 6]]
维度：2
size:6
shape:(2, 3)
步幅:(24, 8)
[[1 4]
 [2 5]
 [3 6]]


In [25]:
import numpy as np
arr = np.arange(12)
print(arr)
arr1 = arr.reshape(3, 4)
print(arr1)

arr2 = arr.reshape(2, -1)  # 2是第一维度是两项， -1 自动推断
print(arr2)

print(np.resize([1,2,3,4], (2, 3)))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[1 2 3]
 [4 1 2]]


In [28]:
!uv add pandas==3.0.3 openpyxl==3.1.5
import pandas as pd
import numpy as np

Resolved 8 packages in 5ms
Checked 6 packages in 0.99ms


In [36]:
pd.Series([10, 20, 30, 40])    
pd.Series([10, 20, 30, 40], index=['a','b','c','d']) 
pd.Series({'a': 10, 'b': 20, 'c': 30}) 
s = pd.Series([10, 20, 30, 40], index=['a','b','c','d'])
s.values
s.index
s.dtype
s.shape

(4,)

In [38]:
pd.DataFrame({
    '姓名': ['张三', '李四', '王五', '赵六'],
    '年龄': [25, 30, 35, 28],
    '城市': ['北京', '上海', '广州', '深圳'],
    '薪资': [15000, 20000, 25000, 18000]
})

arr = np.array([[25,15000],[30,20000],[35,25000]])
pd.DataFrame(arr, columns=['年龄', '薪资'])

,年龄,薪资
0,25,15000
1,30,20000
2,35,25000


In [39]:
pd.read_csv('./linking.csv')

,昵称,学历,城市,经验,薪资,备注
0,Map,本,北京,26应届,实习,NaN
1,yanni*,本,杭州,6年前端\r\n2年转行,前端：20k\r\n转行：28k,新能源企业前端-->产品-->销售-->售前
2,边牧*,本,长沙,5年,9k,离职，空窗期2年，北京17k，React，Flutter
3,决堤*,本科,北京,25应届,9k,被辞退
4,月亮*,专,济南,3年,9k,NaN
...,...,...,...,...,...,...
674,lh*,初中,上海,8年,18k,前端
675,微斯*,本,北京,3.5年,17k,NaN
676,海盐*,专,北京,6.5年,25k->22k->18k,前端
677,wah*,专,上海,7年,20k,前端


In [40]:
pd.read_excel('./linking.xlsx', sheet_name='Sheet1')

,昵称,学历,城市,经验,薪资,备注
0,Map,本,北京,26应届,实习,NaN
1,yanni*,本,杭州,6年前端\n2年转行,前端：20k\n转行：28k,新能源企业前端-->产品-->销售-->售前
2,边牧*,本,长沙,5年,9k,离职，空窗期2年，北京17k，React，Flutter
3,决堤*,本科,北京,25应届,9k,被辞退
4,月亮*,专,济南,3年,9k,NaN
...,...,...,...,...,...,...
674,lh*,初中,上海,8年,18k,前端
675,微斯*,本,北京,3.5年,17k,NaN
676,海盐*,专,北京,6.5年,25k->22k->18k,前端
677,wah*,专,上海,7年,20k,前端


In [41]:
# pd.read_sql: 从数据库读取 SQL 查询结果
import sqlite3

# 创建内存数据库并写入数据
conn = sqlite3.connect(':memory:')
conn.execute('''
    CREATE TABLE employees (
        name TEXT, age INT, city TEXT, salary INT
    )
''')
conn.execute("INSERT INTO employees VALUES ('张三', 25, '北京', 15000)")
conn.execute("INSERT INTO employees VALUES ('李四', 30, '上海', 20000)")
conn.execute("INSERT INTO employees VALUES ('王五', 35, '广州', 25000)")
conn.execute("INSERT INTO employees VALUES ('赵六', 28, '深圳', 18000)")
conn.commit()

df = pd.read_sql('SELECT * FROM employees', conn)
conn.close()
df

,name,age,city,salary
0,张三,25,北京,15000
1,李四,30,上海,20000
2,王五,35,广州,25000
3,赵六,28,深圳,18000
