In [9]:
a = 1
b = 2
print(a + b)

3


In [10]:
print(a * b)

2


In [11]:
!uv add numpy==2.5.1

Resolved 2 packages in 14ms
Checked 1 package in 0.70ms


In [12]:
import numpy as np

In [13]:
arr = np.array([1,2,3, [1,3]])
print(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
print(arr)
print(f'维度：{arr.ndim}')
print(f'size:{arr.size}')
print(f'shape:{arr.shape}')
print(f'步幅:{arr.strides}') # (24, 8)

t = arr.T
print(t) # 和arr公用一块内存空间

[[1 2 3]
 [4 5 6]]
维度：2
size:6
shape:(2, 3)
步幅:(24, 8)
[[1 4]
 [2 5]
 [3 6]]
